/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI - version 0.1.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'knowledgeBaseManagement.get_all_knowledge_base_api_v1_kb_base_get': ['GET', '/api/v1/kb_base'],
  'knowledgeBaseManagement.create_knowledge_base_api_v1_kb_base_post': ['POST', '/api/v1/kb_base'],
  'knowledgeBaseManagement.delete_knowledge_base_api_v1_kb_base__kb_name__delete': [
    'DELETE',
    '/api/v1/kb_base/{kb_name}'
  ],
  'knowledgeBaseManagement.update_kb_schema_api_v1_kb_base__kb_name__schema_post': [
    'POST',
    '/api/v1/kb_base/{kb_name}/schema'
  ],
  'knowledgeBaseManagement.get_kb_schema_api_v1_kb_base__kb_name__schema_exists_get': [
    'GET',
    '/api/v1/kb_base/{kb_name}/schema/exists'
  ],
  'knowledgeBaseFileManagement.get_kb_files_api_v1_kb_base__kb_id__kb_file_get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/kb_file'
  ],
  'knowledgeBaseFileManagement.upload_kb_file_api_v1_kb_base__kb_id__upload_file_post': [
    'POST',
    '/api/v1/kb_base/{kb_id}/upload_file'
  ],
  'knowledgeBaseFileManagement.get_uploaded_file_info_api_v1_kb_base__kb_id__upload_file__file_id__get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/upload_file/{file_id}'
  ],
  'knowledgeBaseFileManagement.ingest_kb_file_api_v1_kb_base__kb_id__ingest_file_post': [
    'POST',
    '/api/v1/kb_base/{kb_id}/ingest_file'
  ],
  'knowledgeBaseFileManagement.ingest_kb_data_api_v1_kb_base__kb_id__ingest_data_post': [
    'POST',
    '/api/v1/kb_base/{kb_id}/ingest_data'
  ],
  'knowledgeBaseDocumentChunkManagement.get_kb_file_chunks_api_v1_kb_base__kb_id__file__file_id__chunks_get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/file/{file_id}/chunks'
  ],
  'knowledgeBaseDocumentChunkManagement.get_kb_chunks_api_v1_kb_base__kb_id__chunks_get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/chunks'
  ],
  'knowledgeBaseRetrievalMethodDynamicManagement.create_kb_query_interface_api_v1_query_interface__kb_name__post': [
    'POST',
    '/api/v1/query_interface/{kb_name}'
  ],
  'knowledgeBaseRetrievalMethodDynamicManagement.get_kb_query_interface_api_v1_query_interface__kb_name__get': [
    'GET',
    '/api/v1/query_interface/{kb_name}'
  ],
  'annotationDataDeposit.deposit_data_api_v1_deposit_post': ['POST', '/api/v1/deposit'],
  'annotationDataDeposit.deposit_batch_api_v1_deposit_batch_post': ['POST', '/api/v1/deposit/batch'],
  'annotationDataManagement.get_data_list_api_v1_data_get': ['GET', '/api/v1/data'],
  'annotationDataManagement.get_data_by_id_api_v1_data__data_id__get': ['GET', '/api/v1/data/{data_id}'],
  'annotationDataManagement.update_annotation_api_v1_data__data_id__annotate_put': [
    'PUT',
    '/api/v1/data/{data_id}/annotate'
  ],
  'annotationDataManagement.approve_data_api_v1_data__data_id__approve_post': [
    'POST',
    '/api/v1/data/{data_id}/approve'
  ],
  'annotationDataManagement.reject_data_api_v1_data__data_id__reject_post': ['POST', '/api/v1/data/{data_id}/reject'],
  'annotationDataManagement.get_by_trace_id_api_v1_data_trace__trace_id__get': ['GET', '/api/v1/data/trace/{trace_id}'],
  'annotationDataManagement.get_by_group_id_api_v1_data_group__group_id__get': ['GET', '/api/v1/data/group/{group_id}'],
  'annotationDataManagement.get_groups_summary_api_v1_data_groups_summary_get': ['GET', '/api/v1/data/groups/summary'],
  'annotationKbIngestion.ingest_to_kb_api_v1_kb_data__data_id__ingest_post': [
    'POST',
    '/api/v1/kb/data/{data_id}/ingest'
  ],
  'annotationKbIngestion.get_kb_status_api_v1_kb_status_get': ['GET', '/api/v1/kb/status'],
  'annotationStatistics.get_overall_stats_api_v1_stats_get': ['GET', '/api/v1/stats'],
  'annotationStatistics.get_pending_p0_stats_api_v1_stats_pending_p0_get': ['GET', '/api/v1/stats/pending-p0'],
  'annotationStatistics.get_stats_by_type_api_v1_stats_by_type_get': ['GET', '/api/v1/stats/by-type'],
  'logConfiguration.get_current_log_level_api_v1_log_level_get': ['GET', '/api/v1/log/level'],
  'logConfiguration.set_log_level_endpoint_api_v1_log_level_post': ['POST', '/api/v1/log/level'],
  'kbWeather.weather_search_rule_0_kb_weather_search_rule_0_post': ['POST', '/kb/weather/search/rule_0'],
  'kbWeather1.weather_search_rule_0_kb_weather_search_rule_0_post': ['POST', '/kb/weather/search/rule_0'],
  'kbWeather.deposit_data_kb_weather_deposit_post': ['POST', '/kb/weather/deposit'],
  'kbWeather1.deposit_data_kb_weather_deposit_post': ['POST', '/kb/weather/deposit'],
  'kbWeather.list_banks_kb_weather_list_banks_get': ['GET', '/kb/weather/list_banks'],
  'kbWeather1.list_banks_kb_weather_list_banks_get': ['GET', '/kb/weather/list_banks'],
  'kbWeatherTemp.weather_temp_search_rule_0_kb_weather_temp_search_rule_0_post': [
    'POST',
    '/kb/weather-temp/search/rule_0'
  ],
  'kbWeatherTemp1.weather_temp_search_rule_0_kb_weather_temp_search_rule_0_post': [
    'POST',
    '/kb/weather-temp/search/rule_0'
  ],
  'kbWeatherTemp.deposit_data_kb_weather_temp_deposit_post': ['POST', '/kb/weather-temp/deposit'],
  'kbWeatherTemp1.deposit_data_kb_weather_temp_deposit_post': ['POST', '/kb/weather-temp/deposit'],
  'kbWeatherTemp.list_banks_kb_weather_temp_list_banks_get': ['GET', '/kb/weather-temp/list_banks'],
  'kbWeatherTemp1.list_banks_kb_weather_temp_list_banks_get': ['GET', '/kb/weather-temp/list_banks'],
  'kbUnstructureDocTest.unstructure_doc_test_search_rule_0_kb_unstructure_doc_test_search_rule_0_post': [
    'POST',
    '/kb/unstructure_doc_test/search/rule_0'
  ],
  'kbUnstructureDocTest1.unstructure_doc_test_search_rule_0_kb_unstructure_doc_test_search_rule_0_post': [
    'POST',
    '/kb/unstructure_doc_test/search/rule_0'
  ],
  'kbUnstructureDocTest.unstructure_doc_test_search_rule_1_kb_unstructure_doc_test_search_rule_1_post': [
    'POST',
    '/kb/unstructure_doc_test/search/rule_1'
  ],
  'kbUnstructureDocTest1.unstructure_doc_test_search_rule_1_kb_unstructure_doc_test_search_rule_1_post': [
    'POST',
    '/kb/unstructure_doc_test/search/rule_1'
  ],
  'kbUnstructureDocTest.deposit_data_kb_unstructure_doc_test_deposit_post': [
    'POST',
    '/kb/unstructure_doc_test/deposit'
  ],
  'kbUnstructureDocTest1.deposit_data_kb_unstructure_doc_test_deposit_post': [
    'POST',
    '/kb/unstructure_doc_test/deposit'
  ],
  'kbUnstructureDocTest.list_banks_kb_unstructure_doc_test_list_banks_get': [
    'GET',
    '/kb/unstructure_doc_test/list_banks'
  ],
  'kbUnstructureDocTest1.list_banks_kb_unstructure_doc_test_list_banks_get': [
    'GET',
    '/kb/unstructure_doc_test/list_banks'
  ],
  'kbQaBank2.qa_bank_2_search_rule_0_kb_qa_bank_2_search_rule_0_post': ['POST', '/kb/qa_bank_2/search/rule_0'],
  'kbQaBank21.qa_bank_2_search_rule_0_kb_qa_bank_2_search_rule_0_post': ['POST', '/kb/qa_bank_2/search/rule_0'],
  'kbQaBank2.deposit_data_kb_qa_bank_2_deposit_post': ['POST', '/kb/qa_bank_2/deposit'],
  'kbQaBank21.deposit_data_kb_qa_bank_2_deposit_post': ['POST', '/kb/qa_bank_2/deposit'],
  'kbQaBank2.list_banks_kb_qa_bank_2_list_banks_get': ['GET', '/kb/qa_bank_2/list_banks'],
  'kbQaBank21.list_banks_kb_qa_bank_2_list_banks_get': ['GET', '/kb/qa_bank_2/list_banks'],
  'kbAnnoBank.anno_bank_search_rule_0_kb_anno_bank_search_rule_0_post': ['POST', '/kb/anno_bank/search/rule_0'],
  'kbAnnoBank1.anno_bank_search_rule_0_kb_anno_bank_search_rule_0_post': ['POST', '/kb/anno_bank/search/rule_0'],
  'kbAnnoBank.deposit_data_kb_anno_bank_deposit_post': ['POST', '/kb/anno_bank/deposit'],
  'kbAnnoBank1.deposit_data_kb_anno_bank_deposit_post': ['POST', '/kb/anno_bank/deposit'],
  'kbAnnoBank.list_banks_kb_anno_bank_list_banks_get': ['GET', '/kb/anno_bank/list_banks'],
  'kbAnnoBank1.list_banks_kb_anno_bank_list_banks_get': ['GET', '/kb/anno_bank/list_banks'],
  'kbTestK.testK_search_rule_0_kb_testK_search_rule_0_post': ['POST', '/kb/testK/search/rule_0'],
  'kbTestK1.testK_search_rule_0_kb_testK_search_rule_0_post': ['POST', '/kb/testK/search/rule_0'],
  'kbTestK.testK_search_rule_1_kb_testK_search_rule_1_post': ['POST', '/kb/testK/search/rule_1'],
  'kbTestK1.testK_search_rule_1_kb_testK_search_rule_1_post': ['POST', '/kb/testK/search/rule_1'],
  'kbTestK.deposit_data_kb_testK_deposit_post': ['POST', '/kb/testK/deposit'],
  'kbTestK1.deposit_data_kb_testK_deposit_post': ['POST', '/kb/testK/deposit'],
  'kbTestK.list_banks_kb_testK_list_banks_get': ['GET', '/kb/testK/list_banks'],
  'kbTestK1.list_banks_kb_testK_list_banks_get': ['GET', '/kb/testK/list_banks'],
  'kbHyyNewStructure1.hyy_new_structure_1_search_rule_0_kb_hyy_new_structure_1_search_rule_0_post': [
    'POST',
    '/kb/hyy_new_structure_1/search/rule_0'
  ],
  'kbHyyNewStructure11.hyy_new_structure_1_search_rule_0_kb_hyy_new_structure_1_search_rule_0_post': [
    'POST',
    '/kb/hyy_new_structure_1/search/rule_0'
  ],
  'kbHyyNewStructure1.deposit_data_kb_hyy_new_structure_1_deposit_post': ['POST', '/kb/hyy_new_structure_1/deposit'],
  'kbHyyNewStructure11.deposit_data_kb_hyy_new_structure_1_deposit_post': ['POST', '/kb/hyy_new_structure_1/deposit'],
  'kbHyyNewStructure1.list_banks_kb_hyy_new_structure_1_list_banks_get': ['GET', '/kb/hyy_new_structure_1/list_banks'],
  'kbHyyNewStructure11.list_banks_kb_hyy_new_structure_1_list_banks_get': ['GET', '/kb/hyy_new_structure_1/list_banks'],
  'kbKbUn.kb_un_search_rule_0_kb_kb_un_search_rule_0_post': ['POST', '/kb/kb_un/search/rule_0'],
  'kbKbUn1.kb_un_search_rule_0_kb_kb_un_search_rule_0_post': ['POST', '/kb/kb_un/search/rule_0'],
  'kbKbUn.kb_un_search_rule_1_kb_kb_un_search_rule_1_post': ['POST', '/kb/kb_un/search/rule_1'],
  'kbKbUn1.kb_un_search_rule_1_kb_kb_un_search_rule_1_post': ['POST', '/kb/kb_un/search/rule_1'],
  'kbKbUn.deposit_data_kb_kb_un_deposit_post': ['POST', '/kb/kb_un/deposit'],
  'kbKbUn1.deposit_data_kb_kb_un_deposit_post': ['POST', '/kb/kb_un/deposit'],
  'kbKbUn.list_banks_kb_kb_un_list_banks_get': ['GET', '/kb/kb_un/list_banks'],
  'kbKbUn1.list_banks_kb_kb_un_list_banks_get': ['GET', '/kb/kb_un/list_banks'],
  'kbTest222.test222_search_rule_0_kb_test222_search_rule_0_post': ['POST', '/kb/test222/search/rule_0'],
  'kbTest2221.test222_search_rule_0_kb_test222_search_rule_0_post': ['POST', '/kb/test222/search/rule_0'],
  'kbTest222.deposit_data_kb_test222_deposit_post': ['POST', '/kb/test222/deposit'],
  'kbTest2221.deposit_data_kb_test222_deposit_post': ['POST', '/kb/test222/deposit'],
  'kbTest222.list_banks_kb_test222_list_banks_get': ['GET', '/kb/test222/list_banks'],
  'kbTest2221.list_banks_kb_test222_list_banks_get': ['GET', '/kb/test222/list_banks'],
  'kbHyyDemo1.hyy_demo_1_search_rule_0_kb_hyy_demo_1_search_rule_0_post': ['POST', '/kb/hyy_demo_1/search/rule_0'],
  'kbHyyDemo11.hyy_demo_1_search_rule_0_kb_hyy_demo_1_search_rule_0_post': ['POST', '/kb/hyy_demo_1/search/rule_0'],
  'kbHyyDemo1.deposit_data_kb_hyy_demo_1_deposit_post': ['POST', '/kb/hyy_demo_1/deposit'],
  'kbHyyDemo11.deposit_data_kb_hyy_demo_1_deposit_post': ['POST', '/kb/hyy_demo_1/deposit'],
  'kbHyyDemo1.list_banks_kb_hyy_demo_1_list_banks_get': ['GET', '/kb/hyy_demo_1/list_banks'],
  'kbHyyDemo11.list_banks_kb_hyy_demo_1_list_banks_get': ['GET', '/kb/hyy_demo_1/list_banks'],
  'kbHyyTest111.hyy_test_111_search_rule_0_kb_hyy_test_111_search_rule_0_post': [
    'POST',
    '/kb/hyy_test_111/search/rule_0'
  ],
  'kbHyyTest1111.hyy_test_111_search_rule_0_kb_hyy_test_111_search_rule_0_post': [
    'POST',
    '/kb/hyy_test_111/search/rule_0'
  ],
  'kbHyyTest111.deposit_data_kb_hyy_test_111_deposit_post': ['POST', '/kb/hyy_test_111/deposit'],
  'kbHyyTest1111.deposit_data_kb_hyy_test_111_deposit_post': ['POST', '/kb/hyy_test_111/deposit'],
  'kbHyyTest111.list_banks_kb_hyy_test_111_list_banks_get': ['GET', '/kb/hyy_test_111/list_banks'],
  'kbHyyTest1111.list_banks_kb_hyy_test_111_list_banks_get': ['GET', '/kb/hyy_test_111/list_banks'],
  'kbTestK2.testK2_search_rule_0_kb_testK2_search_rule_0_post': ['POST', '/kb/testK2/search/rule_0'],
  'kbTestK21.testK2_search_rule_0_kb_testK2_search_rule_0_post': ['POST', '/kb/testK2/search/rule_0'],
  'kbTestK2.testK2_search_rule_1_kb_testK2_search_rule_1_post': ['POST', '/kb/testK2/search/rule_1'],
  'kbTestK21.testK2_search_rule_1_kb_testK2_search_rule_1_post': ['POST', '/kb/testK2/search/rule_1'],
  'kbTestK2.deposit_data_kb_testK2_deposit_post': ['POST', '/kb/testK2/deposit'],
  'kbTestK21.deposit_data_kb_testK2_deposit_post': ['POST', '/kb/testK2/deposit'],
  'kbTestK2.list_banks_kb_testK2_list_banks_get': ['GET', '/kb/testK2/list_banks'],
  'kbTestK21.list_banks_kb_testK2_list_banks_get': ['GET', '/kb/testK2/list_banks'],
  'kbTest3.test3_search_rule_0_kb_test3_search_rule_0_post': ['POST', '/kb/test3/search/rule_0'],
  'kbTest31.test3_search_rule_0_kb_test3_search_rule_0_post': ['POST', '/kb/test3/search/rule_0'],
  'kbTest3.deposit_data_kb_test3_deposit_post': ['POST', '/kb/test3/deposit'],
  'kbTest31.deposit_data_kb_test3_deposit_post': ['POST', '/kb/test3/deposit'],
  'kbTest3.list_banks_kb_test3_list_banks_get': ['GET', '/kb/test3/list_banks'],
  'kbTest31.list_banks_kb_test3_list_banks_get': ['GET', '/kb/test3/list_banks'],
  'kbHyyaaaaaaaaaaa.hyyaaaaaaaaaaa_search_rule_0_kb_hyyaaaaaaaaaaa_search_rule_0_post': [
    'POST',
    '/kb/hyyaaaaaaaaaaa/search/rule_0'
  ],
  'kbHyyaaaaaaaaaaa1.hyyaaaaaaaaaaa_search_rule_0_kb_hyyaaaaaaaaaaa_search_rule_0_post': [
    'POST',
    '/kb/hyyaaaaaaaaaaa/search/rule_0'
  ],
  'kbHyyaaaaaaaaaaa.deposit_data_kb_hyyaaaaaaaaaaa_deposit_post': ['POST', '/kb/hyyaaaaaaaaaaa/deposit'],
  'kbHyyaaaaaaaaaaa1.deposit_data_kb_hyyaaaaaaaaaaa_deposit_post': ['POST', '/kb/hyyaaaaaaaaaaa/deposit'],
  'kbHyyaaaaaaaaaaa.list_banks_kb_hyyaaaaaaaaaaa_list_banks_get': ['GET', '/kb/hyyaaaaaaaaaaa/list_banks'],
  'kbHyyaaaaaaaaaaa1.list_banks_kb_hyyaaaaaaaaaaa_list_banks_get': ['GET', '/kb/hyyaaaaaaaaaaa/list_banks'],
  'kbDaefwasfa1111.daefwasfa1111_search_rule_0_kb_daefwasfa1111_search_rule_0_post': [
    'POST',
    '/kb/daefwasfa1111/search/rule_0'
  ],
  'kbDaefwasfa11111.daefwasfa1111_search_rule_0_kb_daefwasfa1111_search_rule_0_post': [
    'POST',
    '/kb/daefwasfa1111/search/rule_0'
  ],
  'kbDaefwasfa1111.daefwasfa1111_search_rule_1_kb_daefwasfa1111_search_rule_1_post': [
    'POST',
    '/kb/daefwasfa1111/search/rule_1'
  ],
  'kbDaefwasfa11111.daefwasfa1111_search_rule_1_kb_daefwasfa1111_search_rule_1_post': [
    'POST',
    '/kb/daefwasfa1111/search/rule_1'
  ],
  'kbDaefwasfa1111.deposit_data_kb_daefwasfa1111_deposit_post': ['POST', '/kb/daefwasfa1111/deposit'],
  'kbDaefwasfa11111.deposit_data_kb_daefwasfa1111_deposit_post': ['POST', '/kb/daefwasfa1111/deposit'],
  'kbDaefwasfa1111.list_banks_kb_daefwasfa1111_list_banks_get': ['GET', '/kb/daefwasfa1111/list_banks'],
  'kbDaefwasfa11111.list_banks_kb_daefwasfa1111_list_banks_get': ['GET', '/kb/daefwasfa1111/list_banks']
};
